### ISSUE TITLE
Install Instructions Out of Date

### ISSUE THREAD

**Issue by brandon-fsu** [pnnl/socialsim_package#13]
The installation instructions for the package still reference the tarball that used to be in the dist folder, which is no longer part of the repo. The setup.py hasn't been updated in a long time, and after running it, I don't have access to the EvolutionMeasurements class. I have never used an egg before but when I try to do easy_install socialsim.egg-info I get `Processing 
error: Couldn't find a setup script in /home/social-sim/dev/cp2_metrics/socialsim.egg-info`

**Comment by ZachNew** [comment]
Thanks for pointing out this oversight. Looking into it right now. Expect this to be fixed today or tomorrow.

**Comment by brandon-fsu** [comment]
Any updates? Also, will this update include new configuration files for the new evolution measurements?

**Comment by ZachNew** [comment]
Hi Brandon, sorry for the delay. Had some issues pop up on our end. Working on this today. Will have to get back to you about the configuration files.
