### ISSUE TITLE
evolution.py communities

### ISSUE THREAD

**Issue by brandon-fsu** [pnnl/socialsim_package#14]
I'm trying to run the EvolutionMeasurements code to see what everything looks like and I'm running into some issues, and it all seems to revolve around the communities. I am using the scenario 1 ground truth file from the challenge.
First, on line 117: it looks like you should be setting communities, rather than node_list.

Then, I'm getting confused about what communities are supposed to be. For CP2 we got a list of files that had a name community_<community name> and was a list of informationIDs associated with that community. In the evolution class, it looks like the communities are supposed to be from the communityID field of the logs. Two problems: only Reddit has a community ID for scenario 1 according to the schema, but that ground truth file doesn't have that as a field at all, and this goes against the idea of communities from CP2. It also looks to be expecting a list rather than a dictionary. 

Can you provide some clarity here? Thanks.

**Comment by Maria-G** [comment]
Hi Brandon, we have pushed an update to the evolution code so that it follows the same process as the multi_platform measurements. Let us know if that doesn't clear up the confusion.

Thanks!

**Comment by brandon-fsu** [comment]
After installing the new evolution measurements and using the configuration files you sent, I get this error in evolution measurements: 

evolution': {'status': 'Measurements object failed to run.',
    'error': KeyError('run_time')}},
  'youtube': {'social_structure': {'population': {'number_of_nodes': {'status': 'failure',
      'error': AttributeError("'SocialStructureMeasurements' object has no attribute 'gUNig'"),
      'run_time': 0.00024},

The Social Structure measurements also fail for YouTube. Is this coming in another update?

EDIT: additional info. Looking at the output of the measurements running, there seems to be something odd happening:
SOCIALSIM TASKRUNNER   | Instantiating evolution... Done.
SOCIALSIM MEASUREMENTS | Running social_structure node tendency_to_include_URL...

**Comment by Maria-G** [comment]
I'm looking into these issues. We will push an update that includes a fix and release of the CP3 config files soon.

**Comment by Maria-G** [comment]
@brandon-fsu, an update has been pushed to address those taskrunner issues and also includes the CP3 configuration files.

**Comment by brandon-fsu** [comment]
@Maria-G I pulled the latest and installed with python setup.py install. I'm now getting the following errors:
SOCIALSIM TASKRUNNER   | Instantiating multi_platform... 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/social-sim/dev/cp2_metrics/socialsim/run.py", line 189, in run_measurements
    configuration_subset, metadata)
  File "/home/social-sim/dev/cp2_metrics/socialsim/measurements/multi_platform.py", line 28, in __init__
    super(MultiPlatformMeasurements, self).__init__(dataset, configuration, log_file=log_file)
  File "/home/social-sim/dev/cp2_metrics/socialsim/measurements/measurements.py", line 29, in __init__
    for scale in configuration.keys():
AttributeError: 'str' object has no attribute 'keys'

And
SOCIALSIM TASKRUNNER   | Instantiating evolution... 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/socialsim/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'communityID'


I'm also getting odd results for DTW (results in the thousands even though the same log was passed in), and all NRMSE metrics are null. I'm going to email you a copy of the output.
