### ISSUE TITLE
How to avoid calculating ground-truth measurements in multiple evaluation rounds?

### ISSUE THREAD

**Issue by sameeravithana** [pnnl/socialsim_package#15]
In the following code snippet, how to save the ground-truth measurements to be used in the future evaluations? such that you don't have to calculate ground-truth measurements every time.

`
task_runner = ss.TaskRunner(ground_truth, config, metadata=metadata);
results, logs = task_runner(simulation, verbose=True)
`

**Comment by Maria-G** [comment]
You can access the ground-truth measurements results from the task_runner object using the following approach:

`ground_truth_results = task_runner.ground_truth_results`

Or you can save the task_runner object for future evaluations (e.g. with pickle) as the 

`results, logs = task_runner(simulation, verbose=True)`

call can be used for multiple simulations, passing different simulations to `task_runner(simulation, verbose=True)`.
