### ISSUE TITLE
orchestrator.py in docker container has test mode set to true

### ISSUE THREAD

**Issue by hrukalive** [pnnl/socialsim_package#16]
`run_eval` function in the `orchestrator.py` under `/socsim/app/` has the `test=True` set when creating TaskRunner, just to make sure that this behavior is wrong referring to the latest commit to example task runner?

**Comment by dimzar** [comment]
Please use the latest Docker build which has addressed this issue (see https://hub.docker.com/r/pnnl/socialsim)
