### ISSUE TITLE
How does the provided communityID in reddit simulation result affect the measurement?

### ISSUE THREAD

**Issue by hrukalive** [pnnl/socialsim_package#17]
According the coding in measurements, the `self.community_set` with an additional column `community` is generated by `add_communities_to_dataset` in `utils.py`. And upon confirmation, despited the provided `communityID` column in simulation result, `community_set` still assign them according to the informationID specified in each community (as 0, 1, 2, etc). Is this the correct behavior? Where does the communityID affect the measurement?

**Comment by Maria-G** [comment]
Community measurements in CP3 are based off of the informationID groupings reflected in the community files in the directory passed through the metadata object parameter "community_directory" rather than the communityID column in simulation output.

**Comment by hrukalive** [comment]
So the communityID in the Reddit output schema has no meaning?
