### ISSUE TITLE
Dataframes creation question in CascadeEvolutionMeasurements

### ISSUE THREAD

**Issue by hrukalive** [pnnl/socialsim_package#19]
In `evolution.py`, if we have a dataframe with max `nodeTime` like `2018-01-31 14:04:14`, then the end_period will not include it because the granularity is set to month, and the time is default as 00:00:00. Then in the for loop, `ts_platform_df` would be empty. Is this the correct behavior?

```python3
end_period = platform_df[timestamp_col].max().to_period(freq=time_granularity).to_timestamp(how='E') # <- 2018-01-31 00:00:00
self.main_df['{}_period'.format(platform)] = np.nan
self.timestamp_orders[platform] = {}
prev_ts = start_period - pd.Timedelta(seconds=1)

print('in for loop')
for i, ts in enumerate(pd.date_range(start=start_period, end=end_period, freq=time_granularity)):
    ts_end = ts.to_period(freq=time_granularity).to_timestamp(how='E')
    ts_str = self.timestamp_to_str(ts, time_granularity)
    ts_platform_df = platform_df[platform_df[timestamp_col] <= ts_end].copy() # <- empty then
```

**Comment by Maria-G** [comment]
end_period defaults to "23:59:59.999999999" not "00:00:00". So if you have data that only occurs within a single month, e.g. 2018-01-31, then your dataframe would have data for that month because the "end_period" is inclusive up to and including 2018-01-31 23:59:59.999999999

start_period defaults to "00:00:00".

**Comment by hrukalive** [comment]
No, pandas.Period.to_timestamp need to have its freq set to 'S' to have the behavior you mentioned. As the time granularity defaulted to 'M', freq is set to 'D', which will have 00:00:00 problem.
