### ISSUE TITLE
twitter_cascade_reconstruction location prevents socialsim import

### ISSUE THREAD

**Issue by brandon-fsu** [pnnl/socialsim_package#34]
While trying to import the socialsim module from any folder other than socialsim_package/socialsim, there is the following error: 

> In [1]: import socialsim as ss                                                                                                                                      
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-0417f9a59ab0> in <module>
> ----> 1 import socialsim as ss
> 
> /opt/anaconda3/envs/socsim/lib/python3.6/site-packages/socialsim-0.3.0-py3.6.egg/socialsim/__init__.py in <module>
>      15 from .measurements import MetaData
>      16 
> ---> 17 from .extract_ground_truth import extract_reddit_data
>      18 from .extract_ground_truth import extract_github_data
>      19 from .extract_ground_truth import extract_twitter_data
> 
> /opt/anaconda3/envs/socsim/lib/python3.6/site-packages/socialsim-0.3.0-py3.6.egg/socialsim/extract_ground_truth.py in <module>
>      13 from datetime import datetime
>      14 
> ---> 15 from twitter_cascade_reconstruction import full_reconstruction, get_reply_cascade_root_tweet
>      16 
>     
> 
> ModuleNotFoundError: No module named 'twitter_cascade_reconstruction'

I'm trying to use this as part of our evaluation framework and keep our code out of your repository code, so I don't want to work out of that directory.
I installed it using python setup.py install from socialsim_package folder level.

**Comment by Maria-G** [comment]
Thanks for bringing this to our attention. We have switched that call to be a relative import "from .twitter_cascade_reconstruction import ...") so this should be fixed now if you reinstall using setup.py with the latest commit.
