### ISSUE TITLE
Twitter URL data extraction

### ISSUE THREAD

**Issue by kinwaing** [pnnl/socialsim_package#37]
Hi, 

When running the code for twitter URL extraction (def get_twitter_urls(df, name_suffix):), I noticed that the resolved URLs field added by Leidos in extensions might get skipped. The code attempts to access 'socialsim_resolved_urls' field, but I believe Leidos updated the name of this field to simply 'resolved_urls'. 

Thanks,

**Comment by Maria-G** [comment]
Thanks for raising this issue! The latest update includes checks for 'resolved_urls' as well as 'socialsim_resolved_urls' in the extraction process.
