### ISSUE TITLE
validate.py throws an inaccurate error

### ISSUE THREAD

**Issue by alw4ey** [pnnl/socialsim_package#41]
I tried running validate.py on one of our output sample files, and it correctly diagnosed that none of my dates are in the right range, but it says my nodeTimes fall after the simulation period, when they fall before:

-------------Events-------------
*** No nodelist filepath was specified so validation did not check for missing/extra informationIDs. ***

ERRORS:
	There is no data within the simulation period, all nodeTime values occur after the simulation period (2019-02-01 - 2019-02-14).
	Submission nodeTime values -- Min: 2019-01-18 00:00:09 Max: 2019-01-31 23:59:37

**Comment by Maria-G** [comment]
Thanks for raising this issue! The error messages for all dates before vs. all dates after the simulation periods got flipped. I've pushed an update to fix that in validate.py
