### ISSUE TITLE
Github graph ignoring input dataframe

### ISSUE THREAD

**Issue by hrukalive** [pnnl/socialsim_package#42]
I found that the main part of the following code operates on the `main_df`, which does not seem to be correct, especially combined with the following `set()` operation.

https://github.com/pnnl/socialsim_package/blob/904746af6ba72ca46524a64d69aaceab8fdf9239/socialsim/measurements/social_structure.py#L506-L514

**Comment by Maria-G** [comment]
Thanks for raising this issue, we've pushed an update that addresses it.
