### ISSUE TITLE
validate node list

### ISSUE THREAD

**Issue by brandon-fsu** [pnnl/socialsim_package#43]
https://github.com/pnnl/socialsim_package/blob/904746af6ba72ca46524a64d69aaceab8fdf9239/examples/validate.py#L125

The above referenced line attempts to access the dictionary VALID_OPTIONS for 'informationID', but it is never set anywhere in the code. the node list gets passed to the function and only used to check if it exists. I think there was a mixup in how this is supposed to be used.

**Comment by Maria-G** [comment]
Thanks for raising this issue! We've pushed an update to fix this.

**Comment by brandon-fsu** [comment]
While this particular exception is fixed, there is another issue arising from this, and that is that the node list is read in as a list, but passed to `check_all_present` which is expecting a set.
