### ISSUE TITLE
RuntimeWarning: divide by zero encountered in log

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#7]
> /anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/burst_detection/__init__.py:28: RuntimeWarning: divide by zero encountered in log
  return -np.float((log(binomial(int(d),r)) + r*np.log(p) + (d-r)*np.log(1-p)))

**Comment by emily-grace** [comment]
This was caused by passing very short time series to the burst detection algorithm.  We added zero padding the time series for each info ID to cover the full simulation period rather than only the period when activity was observed for that info ID.  This seemed to resolve the issue on my end.
